export const INITIAL_VERIFICATIONS = [
  {
    id: "v1",
    initials: "EM",
    name: "Elena Mitsakis",
    email: "e.mitsakis@gmail.com",
    documentName: "view_license_front.jpg",
    submittedAt: "Today, 08:15 AM",
  },
  {
    id: "v2",
    initials: "AW",
    name: "Aaron Wright",
    email: "aw_design@outlook.com",
    documentName: "DL_Full_2024.pdf",
    submittedAt: "Apr 14, 2026",
  },
  {
    id: "v3",
    initials: "SP",
    name: "Sophia Patel",
    email: "s.patel@techcorp.io",
    documentName: "license_scan_sp.jpg",
    submittedAt: "Apr 13, 2026",
  },
];

export const INITIAL_USERS = [
  {
    id: "u1",
    initials: "JD",
    fullName: "Julianne DeMarco",
    email: "j.demarco@agency.com",
    role: "Owner",
    status: "pending",
    dateRegistered: "Apr 14, 2026",
  },
  {
    id: "u2",
    initials: "RK",
    fullName: "Robert Kincaid",
    email: "rk_mobility@provider.io",
    role: "Owner",
    status: "pending",
    dateRegistered: "Apr 13, 2026",
  },
  {
    id: "u3",
    initials: "NL",
    fullName: "Nina Laurent",
    email: "nina.laurent@mail.fr",
    role: "Renter",
    status: "active",
    dateRegistered: "Apr 10, 2026",
  },
  {
    id: "u4",
    initials: "TC",
    fullName: "Tyler Chen",
    email: "tyler.c@startup.io",
    role: "Owner",
    status: "active",
    dateRegistered: "Apr 8, 2026",
  },
  {
    id: "u5",
    initials: "MA",
    fullName: "Mia Andersson",
    email: "m.andersson@nordic.se",
    role: "Renter",
    status: "suspended",
    dateRegistered: "Mar 29, 2026",
  },
];

export const INITIAL_CAR_POSTS = [
  {
    id: "c1",
    carModel: "Porsche Taycan 2023",
    owner: "Marcus Vane",
    dateSubmitted: "Today, 09:42 AM",
    status: "pending",
    pricePerDay: "$240",
    category: "Electric",
  },
  {
    id: "c2",
    carModel: "BMW i7 M70",
    owner: "Lydia Thorne",
    dateSubmitted: "Apr 14, 2026",
    status: "pending",
    pricePerDay: "$195",
    category: "Luxury",
  },
  {
    id: "c3",
    carModel: "Tesla Model X Plaid",
    owner: "David Chen",
    dateSubmitted: "Apr 14, 2026",
    status: "pending",
    pricePerDay: "$180",
    category: "Electric",
  },
  {
    id: "c4",
    carModel: "Range Rover Sport SVR",
    owner: "Claire Fontaine",
    dateSubmitted: "Apr 12, 2026",
    status: "approved",
    pricePerDay: "$220",
    category: "SUV",
  },
  {
    id: "c5",
    carModel: "Mercedes-AMG GT 63",
    owner: "James Hartley",
    dateSubmitted: "Apr 11, 2026",
    status: "approved",
    pricePerDay: "$260",
    category: "Sports",
  },
  {
    id: "c6",
    carModel: "Audi RS e-tron GT",
    owner: "Yuki Tanaka",
    dateSubmitted: "Apr 9, 2026",
    status: "rejected",
    pricePerDay: "$200",
    category: "Electric",
  },
];

export const INITIAL_RENTALS = [
  {
    id: "r1",
    carModel: "Porsche Taycan 2023",
    renter: "James Carter",
    renterInitials: "JC",
    owner: "Marcus Vane",
    startDate: "Apr 16, 2026",
    endDate: "Apr 20, 2026",
    total: "$960",
    status: "upcoming",
  },
  {
    id: "r2",
    carModel: "Range Rover Sport SVR",
    renter: "Sofia Martinez",
    renterInitials: "SM",
    owner: "Claire Fontaine",
    startDate: "Apr 13, 2026",
    endDate: "Apr 15, 2026",
    total: "$440",
    status: "active",
  },
  {
    id: "r3",
    carModel: "Mercedes-AMG GT 63",
    renter: "Ethan Brooks",
    renterInitials: "EB",
    owner: "James Hartley",
    startDate: "Apr 8, 2026",
    endDate: "Apr 10, 2026",
    total: "$520",
    status: "completed",
  },
  {
    id: "r4",
    carModel: "Tesla Model X Plaid",
    renter: "Aria Wong",
    renterInitials: "AW",
    owner: "David Chen",
    startDate: "Apr 3, 2026",
    endDate: "Apr 6, 2026",
    total: "$540",
    status: "completed",
  },
  {
    id: "r5",
    carModel: "BMW i7 M70",
    renter: "Lucas Fernandez",
    renterInitials: "LF",
    owner: "Lydia Thorne",
    startDate: "Apr 18, 2026",
    endDate: "Apr 21, 2026",
    total: "$585",
    status: "upcoming",
  },
  {
    id: "r6",
    carModel: "Audi RS e-tron GT",
    renter: "Priya Nair",
    renterInitials: "PN",
    owner: "Yuki Tanaka",
    startDate: "Apr 5, 2026",
    endDate: "Apr 6, 2026",
    total: "$200",
    status: "cancelled",
  },
];
